
from automaton import State, Transition, AF
from simulation import simulate_afd
from atg_reader import Token
import sys

def scan(filename, show_prints=False):
    afd = AF()
    tokens = []
    state = State(0, tokens)
    afd.states.append(state)
    afd.initial_state = state
    tokens = []
    tokens.append(Token(id="white", priority=4, regex=[], is_keyword=False, except_keywords=False))
    state = State(7, tokens)
    afd.states.append(state)
    afd.final_states.append(state)
    tokens = []
    tokens.append(Token(id="*", priority=9, regex=[], is_keyword=False, except_keywords=False))
    state = State(8, tokens)
    afd.states.append(state)
    afd.final_states.append(state)
    tokens = []
    tokens.append(Token(id="number", priority=2, regex=[], is_keyword=False, except_keywords=True))
    state = State(9, tokens)
    afd.states.append(state)
    afd.final_states.append(state)
    tokens = []
    state = State(1, tokens)
    afd.states.append(state)
    tokens = []
    tokens.append(Token(id="decnumber", priority=3, regex=[], is_keyword=False, except_keywords=False))
    state = State(10, tokens)
    afd.states.append(state)
    afd.final_states.append(state)
    tokens = []
    tokens.append(Token(id="+", priority=11, regex=[], is_keyword=False, except_keywords=False))
    state = State(11, tokens)
    afd.states.append(state)
    afd.final_states.append(state)
    tokens = []
    tokens.append(Token(id="/", priority=10, regex=[], is_keyword=False, except_keywords=False))
    state = State(12, tokens)
    afd.states.append(state)
    afd.final_states.append(state)
    tokens = []
    state = State(2, tokens)
    afd.states.append(state)
    tokens = []
    tokens.append(Token(id="do", priority=1, regex=[], is_keyword=True, except_keywords=False))
    state = State(13, tokens)
    afd.states.append(state)
    afd.final_states.append(state)
    tokens = []
    tokens.append(Token(id="(", priority=7, regex=[], is_keyword=False, except_keywords=False))
    state = State(14, tokens)
    afd.states.append(state)
    afd.final_states.append(state)
    tokens = []
    tokens.append(Token(id=")", priority=8, regex=[], is_keyword=False, except_keywords=False))
    state = State(15, tokens)
    afd.states.append(state)
    afd.final_states.append(state)
    tokens = []
    tokens.append(Token(id="-", priority=6, regex=[], is_keyword=False, except_keywords=False))
    tokens.append(Token(id="-", priority=6, regex=[], is_keyword=False, except_keywords=False))
    state = State(16, tokens)
    afd.states.append(state)
    afd.final_states.append(state)
    tokens = []
    tokens.append(Token(id=".", priority=14, regex=[], is_keyword=False, except_keywords=False))
    state = State(17, tokens)
    afd.states.append(state)
    afd.final_states.append(state)
    tokens = []
    state = State(3, tokens)
    afd.states.append(state)
    tokens = []
    state = State(4, tokens)
    afd.states.append(state)
    tokens = []
    state = State(5, tokens)
    afd.states.append(state)
    tokens = []
    state = State(6, tokens)
    afd.states.append(state)
    tokens = []
    tokens.append(Token(id="while", priority=0, regex=[], is_keyword=True, except_keywords=False))
    state = State(18, tokens)
    afd.states.append(state)
    afd.final_states.append(state)
    tokens = []
    tokens.append(Token(id=";", priority=13, regex=[], is_keyword=False, except_keywords=False))
    state = State(19, tokens)
    afd.states.append(state)
    afd.final_states.append(state)
    transitions = []
    transition = Transition(current_state=State(0), next_state=State(7), symbol=9)
    transitions.append(transition)
    transition = Transition(current_state=State(7), next_state=State(7), symbol=9)
    transitions.append(transition)
    transition = Transition(current_state=State(7), next_state=State(7), symbol=10)
    transitions.append(transition)
    transition = Transition(current_state=State(7), next_state=State(7), symbol=13)
    transitions.append(transition)
    transition = Transition(current_state=State(7), next_state=State(7), symbol=32)
    transitions.append(transition)
    transition = Transition(current_state=State(0), next_state=State(7), symbol=10)
    transitions.append(transition)
    transition = Transition(current_state=State(0), next_state=State(7), symbol=13)
    transitions.append(transition)
    transition = Transition(current_state=State(0), next_state=State(8), symbol=42)
    transitions.append(transition)
    transition = Transition(current_state=State(0), next_state=State(9), symbol=55)
    transitions.append(transition)
    transition = Transition(current_state=State(9), next_state=State(9), symbol=55)
    transitions.append(transition)
    transition = Transition(current_state=State(9), next_state=State(1), symbol=46)
    transitions.append(transition)
    transition = Transition(current_state=State(1), next_state=State(10), symbol=55)
    transitions.append(transition)
    transition = Transition(current_state=State(10), next_state=State(10), symbol=55)
    transitions.append(transition)
    transition = Transition(current_state=State(10), next_state=State(10), symbol=48)
    transitions.append(transition)
    transition = Transition(current_state=State(10), next_state=State(10), symbol=49)
    transitions.append(transition)
    transition = Transition(current_state=State(10), next_state=State(10), symbol=50)
    transitions.append(transition)
    transition = Transition(current_state=State(10), next_state=State(10), symbol=51)
    transitions.append(transition)
    transition = Transition(current_state=State(10), next_state=State(10), symbol=52)
    transitions.append(transition)
    transition = Transition(current_state=State(10), next_state=State(10), symbol=53)
    transitions.append(transition)
    transition = Transition(current_state=State(10), next_state=State(10), symbol=54)
    transitions.append(transition)
    transition = Transition(current_state=State(10), next_state=State(10), symbol=56)
    transitions.append(transition)
    transition = Transition(current_state=State(10), next_state=State(10), symbol=57)
    transitions.append(transition)
    transition = Transition(current_state=State(1), next_state=State(10), symbol=48)
    transitions.append(transition)
    transition = Transition(current_state=State(1), next_state=State(10), symbol=49)
    transitions.append(transition)
    transition = Transition(current_state=State(1), next_state=State(10), symbol=50)
    transitions.append(transition)
    transition = Transition(current_state=State(1), next_state=State(10), symbol=51)
    transitions.append(transition)
    transition = Transition(current_state=State(1), next_state=State(10), symbol=52)
    transitions.append(transition)
    transition = Transition(current_state=State(1), next_state=State(10), symbol=53)
    transitions.append(transition)
    transition = Transition(current_state=State(1), next_state=State(10), symbol=54)
    transitions.append(transition)
    transition = Transition(current_state=State(1), next_state=State(10), symbol=56)
    transitions.append(transition)
    transition = Transition(current_state=State(1), next_state=State(10), symbol=57)
    transitions.append(transition)
    transition = Transition(current_state=State(9), next_state=State(9), symbol=48)
    transitions.append(transition)
    transition = Transition(current_state=State(9), next_state=State(9), symbol=49)
    transitions.append(transition)
    transition = Transition(current_state=State(9), next_state=State(9), symbol=50)
    transitions.append(transition)
    transition = Transition(current_state=State(9), next_state=State(9), symbol=51)
    transitions.append(transition)
    transition = Transition(current_state=State(9), next_state=State(9), symbol=52)
    transitions.append(transition)
    transition = Transition(current_state=State(9), next_state=State(9), symbol=53)
    transitions.append(transition)
    transition = Transition(current_state=State(9), next_state=State(9), symbol=54)
    transitions.append(transition)
    transition = Transition(current_state=State(9), next_state=State(9), symbol=56)
    transitions.append(transition)
    transition = Transition(current_state=State(9), next_state=State(9), symbol=57)
    transitions.append(transition)
    transition = Transition(current_state=State(0), next_state=State(11), symbol=43)
    transitions.append(transition)
    transition = Transition(current_state=State(0), next_state=State(7), symbol=32)
    transitions.append(transition)
    transition = Transition(current_state=State(0), next_state=State(12), symbol=47)
    transitions.append(transition)
    transition = Transition(current_state=State(0), next_state=State(2), symbol=100)
    transitions.append(transition)
    transition = Transition(current_state=State(2), next_state=State(13), symbol=111)
    transitions.append(transition)
    transition = Transition(current_state=State(0), next_state=State(14), symbol=40)
    transitions.append(transition)
    transition = Transition(current_state=State(0), next_state=State(15), symbol=41)
    transitions.append(transition)
    transition = Transition(current_state=State(0), next_state=State(16), symbol=45)
    transitions.append(transition)
    transition = Transition(current_state=State(0), next_state=State(17), symbol=46)
    transitions.append(transition)
    transition = Transition(current_state=State(0), next_state=State(9), symbol=48)
    transitions.append(transition)
    transition = Transition(current_state=State(0), next_state=State(9), symbol=49)
    transitions.append(transition)
    transition = Transition(current_state=State(0), next_state=State(9), symbol=50)
    transitions.append(transition)
    transition = Transition(current_state=State(0), next_state=State(9), symbol=51)
    transitions.append(transition)
    transition = Transition(current_state=State(0), next_state=State(9), symbol=52)
    transitions.append(transition)
    transition = Transition(current_state=State(0), next_state=State(9), symbol=53)
    transitions.append(transition)
    transition = Transition(current_state=State(0), next_state=State(9), symbol=54)
    transitions.append(transition)
    transition = Transition(current_state=State(0), next_state=State(3), symbol=119)
    transitions.append(transition)
    transition = Transition(current_state=State(3), next_state=State(4), symbol=104)
    transitions.append(transition)
    transition = Transition(current_state=State(4), next_state=State(5), symbol=105)
    transitions.append(transition)
    transition = Transition(current_state=State(5), next_state=State(6), symbol=108)
    transitions.append(transition)
    transition = Transition(current_state=State(6), next_state=State(18), symbol=101)
    transitions.append(transition)
    transition = Transition(current_state=State(0), next_state=State(9), symbol=56)
    transitions.append(transition)
    transition = Transition(current_state=State(0), next_state=State(9), symbol=57)
    transitions.append(transition)
    transition = Transition(current_state=State(0), next_state=State(19), symbol=59)
    transitions.append(transition)
    afd.transitions = transitions
    afd.assign_state_numbers()
    ignore_set = set(set())

    with open(filename, encoding='utf-8') as fp:
        string = fp.read()

    char_array = []

    for s in string:
        if(ord(s) not in ignore_set):
            char_array.append(ord(s))


    tokens = simulate_afd(afd, char_array, show_prints)
    return tokens

if __name__ == "__main__":
    if(len(sys.argv) == 2):
        filename = sys.argv[1]
        scan(filename, True)
    else:
        print('ARGUMENTOS INVALIDOS')
